#!/usr/bin/env python3
"""反舰 / 对陆攻击 / 反潜导弹分册：Family -> Variant 数据表。

ID 严格遵循 WEAPON_ID_ROSTER.md；几何参数只能使用 weapon_records.GEOMETRY_DEFAULTS
中声明的字段，保证 Blender 工厂可以直接消费。只记录公开资料中的身份、类别、
时代、外形轮廓与游戏科技树分层，不含任何工程或制造细节。
"""
from __future__ import annotations

from weapon_records import SOURCES, dim, family, geo, variant


def _entry(
    weapon_id, display_name, short_name, category, role, subrole, era, years, tier,
    tier_reason, guidance, propulsion, launch_methods, role_tags, dims, priority,
    kind, features, sources, status, notes='', **params
):
    return variant(
        weapon_id, display_name, short_name, category, role, subrole, era, years,
        tier, tier_reason, guidance, propulsion, launch_methods, role_tags, dims,
        priority, geo(kind, features, **params), 'PUBLIC', sources, status, notes=notes,
    )


MISSILE_FAMILIES = [
    # ===================================================================
    # 俄罗斯 / 苏联 —— 反舰导弹
    # ===================================================================
    family(
        'RU_ASM_P5', 'Russia', 'P-5 Pyatyorka', 'ASM', ['ASM'], 'ru_asm_p5',
        [
            _entry(
                'RU_ASM_P5', 'P-5 Pyatyorka', 'P-5', 'ASM',
                '早期潜射反舰巡航导弹', 'Early_Cruise', 'Cold War', '1959-1960s',
                3,
                '游戏 T3 潜射巡航导弹起点：需要上浮发射、外形粗短、固定大展弦比弹翼，视觉上与现代导弹差异极大。',
                '无线电指令 + 惯性', '涡轮喷气 + 固体助推',
                ['SURFACE_LAUNCH', 'DECK_MOUNT'], ['anti_ship', 'early_cruise'],
                dim(10.0, 1.0, 4000, 'ESTIMATED', '公开资料为级别近似。'),
                'MEDIUM', 'cruise_missile', ['surface_launch', 'large_fixed_wing'],
                [SOURCES['RU_SHIPS'], SOURCES['RU_FAS']], 'HISTORICAL',
                nose='blunt', nose_len_ratio=2.0, wing_type='fixed', wing_pairs=1,
                wing_span_ratio=4.6, wing_chord_ratio=1.6, wing_position=0.45,
                wing_sweep_deg=12.0, tail_type='cruciform', tail_span_ratio=2.4,
                booster=1, booster_len_ratio=0.2, bands=1,
            ),
            _entry(
                'RU_ASM_P6', 'P-6 Progress', 'P-6', 'ASM',
                '冷战早期远程反舰导弹', 'Early_Cruise', 'Cold War', '1960s-1970s',
                3,
                '游戏 T3 远程分支：与 P-5 共享弹体几何，首部进气道与制导组件不同。',
                '雷达 + 惯性', '涡轮喷气 + 固体助推',
                ['SURFACE_LAUNCH', 'DECK_MOUNT'], ['anti_ship', 'long_range'],
                dim(10.6, 0.9, 4500, 'ESTIMATED', '沿用同族级别近似。'),
                'LOW', 'cruise_missile', ['surface_launch', 'nose_intake'],
                [SOURCES['RU_SHIPS']], 'HISTORICAL',
                nose='blunt', nose_len_ratio=1.8, wing_type='folding', wing_pairs=1,
                wing_span_ratio=4.2, wing_chord_ratio=1.4, wing_position=0.4,
                wing_sweep_deg=20.0, tail_type='cruciform', tail_span_ratio=2.6,
                intake_type='chin', intake_position=0.15, intake_len_ratio=1.6,
                booster=1, booster_len_ratio=0.22, bands=2,
            ),
        ],
        notes='P-6 是 P-5 家族的后续型号，共享基础几何，仅在数据层区分。',
    ),
    family(
        'RU_ASM_P70', 'Russia', 'P-70 Ametist', 'ASM', ['ASM'], 'ru_asm_p70',
        [
            _entry(
                'RU_ASM_P70', 'P-70 Ametist', 'P-70', 'ASM',
                '水下发射反舰导弹', 'Underwater_Launch_Cruise', 'Cold War', '1968-1990s',
                4,
                '游戏 T4 水下发射分支起点：533 毫米发射管布放、折叠弹翼，与上浮发射的早期型号外形完全不同。',
                '雷达 + 惯性', '涡轮喷气 + 固体助推',
                ['TORPEDO_TUBE', 'CANISTER'], ['anti_ship', 'underwater_launch'],
                dim(7.0, 0.55, 2900, 'PUBLIC_REFERENCE', '公开资料长度约 7 米，与 533 毫米发射管匹配。'),
                'HIGH', 'cruise_missile', ['underwater_launch', 'folding_wing', 'canister'],
                [SOURCES['RU_SHIPS'], SOURCES['RU_FAS']], 'HISTORICAL',
                nose='ogive', nose_len_ratio=2.4, wing_type='folding', wing_pairs=1,
                wing_span_ratio=3.8, wing_chord_ratio=1.2, wing_position=0.38,
                wing_sweep_deg=32.0, tail_type='cruciform', tail_span_ratio=2.2,
                booster=1, booster_len_ratio=0.26, booster_fins=4, bands=2, canister=1,
            ),
        ],
    ),
    family(
        'RU_ASM_P120', 'Russia', 'P-120 Malakhit', 'ASM', ['ASM'], 'ru_asm_p120',
        [
            _entry(
                'RU_ASM_P120', 'P-120 Malakhit', 'P-120', 'ASM',
                '冷战反舰巡航导弹（潜射型）', 'Cold_War_Cruise', 'Cold War', '1970s-1990s',
                5,
                '游戏 T5 中段节点：弹体比 P-70 更粗，短粗外形便于与后续型号区分。',
                '雷达 + 惯性', '涡轮喷气 + 固体助推',
                ['TORPEDO_TUBE'], ['anti_ship'],
                dim(5.0, 0.55, 2900, 'ESTIMATED', '公开资料为级别近似。'),
                'MEDIUM', 'cruise_missile', ['tube_launched', 'folding_wing'],
                [SOURCES['RU_SHIPS']], 'HISTORICAL',
                nose='ogive', nose_len_ratio=2.0, wing_type='folding', wing_pairs=1,
                wing_span_ratio=3.2, wing_chord_ratio=1.1, wing_position=0.4,
                wing_sweep_deg=30.0, tail_type='cruciform', tail_span_ratio=2.0,
                booster=1, booster_len_ratio=0.24, bands=2, canister=1,
            ),
        ],
    ),
    family(
        'RU_ASM_P500', 'Russia', 'P-500 Bazalt', 'ASM', ['ASM'], 'ru_asm_p500',
        [
            _entry(
                'RU_ASM_P500', 'P-500 Bazalt', 'P-500', 'ASM',
                '重型超音速反舰导弹', 'Supersonic_Anti_Ship', 'Cold War', '1975-present',
                6,
                '游戏 T6 超音速反舰主力：固体助推 + 冲压主级，尾翼与进气道结构清晰。',
                '雷达 + 惯性', '冲压发动机 + 固体助推',
                ['VLS', 'TORPEDO_TUBE'], ['anti_ship', 'supersonic'],
                dim(11.7, 0.88, 4800, 'PUBLIC_REFERENCE', '公开资料长度约 11.7 米。'),
                'HIGH', 'supersonic_missile', ['ramjet', 'solid_booster', 'large_tail'],
                [SOURCES['RU_SHIPS'], SOURCES['RU_FAS']], 'HISTORICAL',
                nose='conical', nose_len_ratio=3.2, wing_type='fixed', wing_pairs=1,
                wing_span_ratio=2.4, wing_chord_ratio=1.5, wing_position=0.55,
                wing_sweep_deg=52.0, tail_type='cruciform', tail_span_ratio=2.4,
                intake_type='four', intake_position=0.26, intake_len_ratio=1.8,
                booster=1, booster_len_ratio=0.24, booster_fins=4, bands=2,
            ),
            _entry(
                'RU_ASM_P1000', 'P-1000 Vulkan', 'P-1000', 'ASM',
                '超音速反舰导弹改进型', 'Supersonic_Anti_Ship', 'Cold War Late', '1980s-present',
                7,
                '游戏 T7 改进型：与 Bazalt 共享基础几何，数据层区分射程与制导代次。',
                '雷达 + 惯性', '冲压发动机 + 固体助推',
                ['VLS', 'TORPEDO_TUBE'], ['anti_ship', 'supersonic', 'long_range'],
                dim(11.7, 0.88, 4800, 'ESTIMATED', '沿用同族级别近似。'),
                'MEDIUM', 'supersonic_missile', ['ramjet', 'solid_booster', 'long_range'],
                [SOURCES['RU_SHIPS']], 'HISTORICAL',
                nose='conical', nose_len_ratio=3.4, wing_type='fixed', wing_pairs=1,
                wing_span_ratio=2.4, wing_chord_ratio=1.5, wing_position=0.55,
                wing_sweep_deg=52.0, tail_type='cruciform', tail_span_ratio=2.4,
                intake_type='four', intake_position=0.26, intake_len_ratio=1.8,
                booster=1, booster_len_ratio=0.24, booster_fins=4, bands=3, windows=1,
            ),
        ],
        notes='Vulkan 是 Bazalt 家族的远程改进型，共享基础几何。',
    ),
    family(
        'RU_ASM_P700', 'Russia', 'P-700 Granit', 'ASM', ['ASM'], 'ru_asm_p700',
        [
            _entry(
                'RU_ASM_P700', 'P-700 Granit', 'P-700', 'ASM',
                '冷战后期重型超音速反舰导弹', 'Supersonic_Anti_Ship', 'Cold War Late', '1980s-present',
                7,
                '游戏 T7 俄罗斯标志性远程反舰导弹：长弹体、双进气口与大型尾控制面，镜头分辨度高。',
                '雷达 + 惯性', '冲压发动机 + 固体助推',
                ['VLS', 'TORPEDO_TUBE'], ['anti_ship', 'supersonic', 'long_range'],
                dim(10.0, 0.85, 7000, 'PUBLIC_REFERENCE', '公开资料长度约 10 米。'),
                'HIGH', 'supersonic_missile', ['ramjet', 'solid_booster', 'twin_intakes'],
                [SOURCES['RU_SHIPS'], SOURCES['RU_FAS']], 'RETIRED',
                nose='conical', nose_len_ratio=3.0, wing_type='fixed', wing_pairs=1,
                wing_span_ratio=2.3, wing_chord_ratio=1.4, wing_position=0.5,
                wing_sweep_deg=55.0, tail_type='cruciform', tail_span_ratio=2.3,
                intake_type='side', intake_position=0.24, intake_len_ratio=2.0,
                booster=1, booster_len_ratio=0.22, booster_fins=4, bands=2, windows=1,
            ),
        ],
    ),
    family(
        'RU_ASM_Oniks', 'Russia', 'P-800 Oniks', 'ASM', ['ASM'], 'ru_asm_oniks',
        [
            _entry(
                'RU_ASM_Oniks', 'P-800 Oniks', 'Oniks', 'ASM',
                '现代超音速反舰导弹', 'Supersonic_Anti_Ship', 'Modern', '2002-present',
                8,
                '游戏 T8 现代超音速主力：细长弹体与一体式助推段，是 Yasen 级的核心反舰载荷。',
                '主动雷达 + 惯性', '冲压发动机 + 固体助推',
                ['VLS', 'TORPEDO_TUBE'], ['anti_ship', 'supersonic', 'modern'],
                dim(8.9, 0.67, 3000, 'PUBLIC_REFERENCE', '公开资料长度约 8.9 米。'),
                'HIGH', 'supersonic_missile', ['ramjet', 'solid_booster', 'slim_body'],
                [SOURCES['RU_SHIPS'], SOURCES['RU_FAS']], 'ACTIVE',
                nose='conical', nose_len_ratio=3.6, wing_type='fixed', wing_pairs=1,
                wing_span_ratio=1.9, wing_chord_ratio=1.2, wing_position=0.6,
                wing_sweep_deg=58.0, tail_type='cruciform', tail_span_ratio=2.0,
                intake_type='four', intake_position=0.3, intake_len_ratio=1.6,
                booster=1, booster_len_ratio=0.3, booster_fins=4, bands=3, windows=1, canister=1,
            ),
        ],
    ),
    family(
        'RU_ASM_Zircon', 'Russia', '3M22 Tsirkon', 'ASM', ['ASM'], 'ru_asm_zircon',
        [
            _entry(
                'RU_ASM_Zircon', '3M22 Tsirkon', 'Zircon', 'ASM',
                '新一代高超音速反舰导弹', 'Hypersonic_Anti_Ship', 'Modern', '2020s-present',
                10,
                '游戏 T10 顶级反舰节点：与常规冲压导弹外形明显不同，弹体短粗、控制面小。',
                '主动雷达 + 惯性', '超燃冲压（公开描述）',
                ['VLS'], ['anti_ship', 'hypersonic', 'modern'],
                dim(9.0, 0.6, 3000, 'ESTIMATED', '公开资料为级别近似。'),
                'HIGH', 'glide_body', ['hypersonic', 'small_control_surfaces'],
                [SOURCES['RU_FAS']], 'ACTIVE',
                body_shape='wedge', nose='blunt', nose_len_ratio=1.6, fin_count=2,
                fin_span_ratio=1.6, fin_chord_ratio=1.2, tail_type='flaps',
                booster=1, booster_len_ratio=0.35, bands=2,
            ),
        ],
    ),
    family(
        'RU_MISSILE_Kalibr', 'Russia', 'Kalibr family', 'ASM', ['ASM', 'LAM'], 'ru_missile_kalibr',
        [
            _entry(
                'RU_ASM_Kalibr_3M54', 'Kalibr 3M54', '3M54', 'ASM',
                '现代反舰巡航导弹', 'Modern_Cruise', 'Modern', '1990s-present',
                8,
                '游戏 T8 现代反舰巡航导弹：发射管布放、弹翼折叠，末段自带独立超音速级。',
                '惯性 + 主动雷达', '涡喷 + 固体助推',
                ['TORPEDO_TUBE', 'VLS'], ['anti_ship', 'modern', 'underwater_launch'],
                dim(8.2, 0.533, 2300, 'PUBLIC_REFERENCE', '公开资料与 533 毫米发射管匹配。'),
                'HIGH', 'cruise_missile', ['underwater_launch', 'folding_wing', 'terminal_stage'],
                [SOURCES['RU_SHIPS'], SOURCES['RU_FAS']], 'ACTIVE',
                nose='ogive', nose_len_ratio=2.6, wing_type='folding', wing_pairs=1,
                wing_span_ratio=3.6, wing_chord_ratio=1.1, wing_position=0.36,
                wing_sweep_deg=34.0, tail_type='cruciform', tail_span_ratio=2.0,
                booster=1, booster_len_ratio=0.3, booster_fins=4, bands=3, windows=1, canister=1,
            ),
            _entry(
                'RU_LAM_Kalibr_3M14', 'Kalibr 3M14', '3M14', 'LAM',
                '现代对陆攻击巡航导弹', 'Modern_Cruise', 'Modern', '2000s-present',
                8,
                '游戏 T8 对陆攻击节点：与反舰型共享发射系统，弹翼展开后是典型巡航导弹外形。',
                '惯性 + 卫星定位 + 地形匹配', '涡喷 + 固体助推',
                ['TORPEDO_TUBE', 'VLS'], ['land_attack', 'modern', 'long_range'],
                dim(6.2, 0.533, 1800, 'PUBLIC_REFERENCE', '公开资料与发射管口径匹配。'),
                'HIGH', 'cruise_missile', ['underwater_launch', 'popout_wing', 'long_range'],
                [SOURCES['RU_SHIPS'], SOURCES['RU_FAS']], 'ACTIVE',
                nose='ogive', nose_len_ratio=2.8, wing_type='popout', wing_pairs=1,
                wing_span_ratio=4.0, wing_chord_ratio=1.2, wing_position=0.42,
                wing_sweep_deg=28.0, tail_type='cruciform', tail_span_ratio=2.0,
                booster=1, booster_len_ratio=0.3, booster_fins=4, bands=3, canister=1,
            ),
        ],
        notes='Kalibr 是家族而非单一型号：反舰型与对陆型共享发射系统但角色不同，必须分开记录。',
    ),

    # ===================================================================
    # 美国
    # ===================================================================
    family(
        'US_ASM_Harpoon', 'USA', 'Harpoon (UGM-84)', 'ASM', ['ASM'], 'us_asm_harpoon',
        [
            _entry(
                'US_ASM_Harpoon', 'UGM-84 Sub-Harpoon', 'Harpoon', 'ASM',
                '潜射反舰巡航导弹', 'Modern_Cruise', 'Cold War Late', '1980s-2000s',
                6,
                '游戏 T6 美国潜射反舰节点：短弹体、十字弹翼、发射管封装，与其他导弹外形差异明显。',
                '惯性 + 主动雷达', '涡喷 + 固体助推',
                ['TORPEDO_TUBE', 'CANISTER'], ['anti_ship', 'underwater_launch'],
                dim(4.6, 0.34, 700, 'PUBLIC_REFERENCE', '公开资料长度约 4.6 米。'),
                'HIGH', 'cruise_missile', ['underwater_launch', 'cruciform_wing', 'canister'],
                [SOURCES['US_NAVY'], SOURCES['RTX']], 'RETIRED',
                nose='blunt', nose_len_ratio=1.6, wing_type='fixed', wing_pairs=1,
                wing_span_ratio=2.4, wing_chord_ratio=1.0, wing_position=0.4,
                wing_sweep_deg=30.0, tail_type='cruciform', tail_span_ratio=1.8,
                booster=1, booster_len_ratio=0.22, booster_fins=4, bands=2, windows=1, canister=1,
            ),
        ],
    ),
    family(
        'US_LAM_Tomahawk', 'USA', 'Tomahawk', 'LAM', ['LAM', 'ASM'], 'us_lam_tomahawk',
        [
            _entry(
                'US_LAM_Tomahawk', 'BGM-109 Tomahawk', 'Tomahawk', 'LAM',
                '早期对陆攻击巡航导弹', 'Modern_Cruise', 'Cold War Late', '1980s-1990s',
                6,
                '游戏 T6 对陆攻击起点：发射管布放、弹翼弹出，是巡航导弹的基础几何。',
                '惯性 + 地形匹配', '涡喷 + 固体助推',
                ['TORPEDO_TUBE', 'VLS'], ['land_attack', 'long_range'],
                dim(5.56, 0.52, 1200, 'ESTIMATED', 'Block II 级尺寸按公开资料近似。'),
                'MEDIUM', 'cruise_missile', ['underwater_launch', 'popout_wing'],
                [SOURCES['US_NAVY'], SOURCES['US_FAS']], 'RETIRED',
                nose='blunt', nose_len_ratio=2.2, wing_type='popout', wing_pairs=1,
                wing_span_ratio=3.2, wing_chord_ratio=1.0, wing_position=0.42,
                wing_sweep_deg=30.0, tail_type='cruciform', tail_span_ratio=1.9,
                booster=1, booster_len_ratio=0.3, booster_fins=4, bands=2, canister=1,
            ),
            _entry(
                'US_LAM_Tomahawk_BlockIII', 'Tomahawk Block III', 'TACTOM III', 'LAM',
                '对陆攻击巡航导弹', 'Modern_Cruise', 'Cold War Late', '1990s-2000s',
                7,
                '游戏 T7 成熟批次：与早期型共享弹体几何，数据层区分制导与射程代次。',
                '惯性 + 地形匹配 + 卫星定位', '涡喷 + 固体助推',
                ['TORPEDO_TUBE', 'VLS'], ['land_attack', 'long_range'],
                dim(6.25, 0.52, 1600, 'PUBLIC_REFERENCE', '公开资料长度约 6.25 米。'),
                'HIGH', 'cruise_missile', ['underwater_launch', 'popout_wing', 'long_range'],
                [SOURCES['US_NAVY']], 'RETIRED',
                nose='blunt', nose_len_ratio=2.0, wing_type='popout', wing_pairs=1,
                wing_span_ratio=3.4, wing_chord_ratio=1.0, wing_position=0.42,
                wing_sweep_deg=30.0, tail_type='cruciform', tail_span_ratio=1.9,
                booster=1, booster_len_ratio=0.28, booster_fins=4, bands=2, canister=1,
            ),
            _entry(
                'US_LAM_Tomahawk_BlockIV', 'Tomahawk Block IV', 'TACTOM IV', 'LAM',
                '现代对陆攻击巡航导弹', 'Modern_Cruise', 'Modern', '2004-present',
                8,
                '游戏 T8 现役主力：与 Block III 共享几何，增加数据链天线分带与可重新瞄准能力标注。',
                '惯性 + 卫星定位 + 数据链', '涡喷 + 固体助推',
                ['TORPEDO_TUBE', 'VLS'], ['land_attack', 'modern', 'long_range', 'net_enabled'],
                dim(6.25, 0.52, 1600, 'PUBLIC_REFERENCE', '与 Block III 同级尺寸。'),
                'HIGH', 'cruise_missile', ['underwater_launch', 'popout_wing', 'datalink_antenna'],
                [SOURCES['US_NAVY'], SOURCES['RTX']], 'ACTIVE',
                nose='blunt', nose_len_ratio=2.0, wing_type='popout', wing_pairs=1,
                wing_span_ratio=3.4, wing_chord_ratio=1.0, wing_position=0.42,
                wing_sweep_deg=30.0, tail_type='cruciform', tail_span_ratio=1.9,
                booster=1, booster_len_ratio=0.28, booster_fins=4, bands=3, windows=1, canister=1,
            ),
            _entry(
                'US_LAM_Tomahawk_BlockV', 'Tomahawk Block V', 'TACTOM V', 'LAM',
                '现代多用途巡航导弹', 'Modern_Cruise', 'Modern', '2020s-present',
                9,
                '游戏 T9 最新批次：与 Block IV 共享弹体几何，数据层区分任务模块与批次。',
                '惯性 + 卫星定位 + 数据链', '涡喷 + 固体助推',
                ['TORPEDO_TUBE', 'VLS'], ['land_attack', 'anti_ship', 'modern', 'multi_role'],
                dim(6.25, 0.52, 1600, 'ESTIMATED', '公开资料为同族尺寸。'),
                'HIGH', 'cruise_missile', ['underwater_launch', 'popout_wing', 'multi_role_kit'],
                [SOURCES['US_NAVY']], 'ACTIVE',
                nose='blunt', nose_len_ratio=2.0, wing_type='popout', wing_pairs=1,
                wing_span_ratio=3.4, wing_chord_ratio=1.0, wing_position=0.42,
                wing_sweep_deg=30.0, tail_type='cruciform', tail_span_ratio=1.9,
                booster=1, booster_len_ratio=0.28, booster_fins=4, bands=4, windows=2, canister=1,
            ),
            _entry(
                'US_ASM_Tomahawk_TASM', 'BGM-109B TASM', 'TASM', 'ASM',
                '反舰型巡航导弹（已退役）', 'Modern_Cruise', 'Cold War Late', '1980s-1990s',
                6,
                '游戏 T6 反舰分支：与对陆型共享弹体几何，导引头与标识不同。',
                '惯性 + 主动雷达', '涡喷 + 固体助推',
                ['TORPEDO_TUBE', 'VLS'], ['anti_ship', 'retired'],
                dim(6.25, 0.52, 1600, 'PUBLIC_REFERENCE', '与同族同级尺寸。'),
                'MEDIUM', 'cruise_missile', ['underwater_launch', 'popout_wing', 'radar_seeker'],
                [SOURCES['US_FAS']], 'RETIRED',
                nose='blunt', nose_len_ratio=2.0, wing_type='popout', wing_pairs=1,
                wing_span_ratio=3.4, wing_chord_ratio=1.0, wing_position=0.42,
                wing_sweep_deg=30.0, tail_type='cruciform', tail_span_ratio=1.9,
                booster=1, booster_len_ratio=0.28, booster_fins=4, bands=2, windows=1, canister=1,
            ),
        ],
        notes='Tomahawk 是武器家族：不同批次与反舰型共享基础几何，只在数据层区分。',
    ),

    # ===================================================================
    # 法国 / 中国
    # ===================================================================
    family(
        'FR_ASM_Exocet_SM39', 'France', 'Exocet SM39', 'ASM', ['ASM'], 'fr_asm_sm39',
        [
            _entry(
                'FR_ASM_Exocet_SM39', 'Exocet SM39', 'SM39', 'ASM',
                '潜射反舰巡航导弹', 'Modern_Cruise', 'Cold War Late', '1980s-present',
                7,
                '游戏 T7 法国反舰主力：短粗弹体 + 环形助推段，与美制鱼叉外形可区分。',
                '惯性 + 主动雷达', '固体助推 + 续航发动机',
                ['TORPEDO_TUBE', 'CANISTER'], ['anti_ship', 'underwater_launch'],
                dim(4.7, 0.35, 655, 'PUBLIC_REFERENCE', '公开资料长度约 4.7 米。'),
                'HIGH', 'cruise_missile', ['underwater_launch', 'cruciform_wing', 'ring_booster'],
                [SOURCES['MBDA']], 'ACTIVE',
                nose='blunt', nose_len_ratio=1.4, wing_type='fixed', wing_pairs=1,
                wing_span_ratio=2.3, wing_chord_ratio=0.9, wing_position=0.38,
                wing_sweep_deg=32.0, tail_type='cruciform', tail_span_ratio=1.7,
                booster=1, booster_len_ratio=0.24, booster_fins=4, bands=2, windows=1, canister=1,
            ),
        ],
    ),
    family(
        'FR_LAM_MdCN', 'France', 'MdCN', 'LAM', ['LAM'], 'fr_lam_mdcn',
        [
            _entry(
                'FR_LAM_MdCN', 'MdCN / SCALP Naval', 'MdCN', 'LAM',
                '对陆攻击巡航导弹', 'Modern_Cruise', 'Modern', '2010s-present',
                8,
                '游戏 T8 法国对陆攻击节点：经发射管布放的长弹体巡航导弹，与反舰型外形差异明显。',
                '惯性 + 卫星定位 + 地形匹配', '涡喷 + 固体助推',
                ['TORPEDO_TUBE'], ['land_attack', 'modern', 'long_range'],
                dim(6.5, 0.533, 1400, 'ESTIMATED', '公开资料为级别近似。'),
                'HIGH', 'cruise_missile', ['underwater_launch', 'popout_wing', 'long_range'],
                [SOURCES['MBDA']], 'ACTIVE',
                nose='ogive', nose_len_ratio=2.6, wing_type='popout', wing_pairs=1,
                wing_span_ratio=4.2, wing_chord_ratio=1.1, wing_position=0.44,
                wing_sweep_deg=26.0, tail_type='cruciform', tail_span_ratio=2.1,
                booster=1, booster_len_ratio=0.3, booster_fins=4, bands=2, canister=1,
            ),
        ],
    ),
    family(
        'CN_ASM_YJ8', 'China', 'YJ-8 / YJ-82', 'ASM', ['ASM'], 'cn_asm_yj8',
        [
            _entry(
                'CN_ASM_YJ8', 'YJ-8 / YJ-82', 'YJ-8', 'ASM',
                '潜射反舰巡航导弹', 'Modern_Cruise', 'Cold War Late', '1980s-present',
                6,
                '游戏 T6 中国反舰起点：发射管布放、弹体较短，固定弹翼比例明显。',
                '惯性 + 主动雷达', '固体助推 + 续航发动机',
                ['TORPEDO_TUBE', 'CANISTER'], ['anti_ship', 'underwater_launch'],
                dim(5.8, 0.36, 815, 'ESTIMATED', '公开资料为级别近似。'),
                'MEDIUM', 'cruise_missile', ['underwater_launch', 'fixed_wing'],
                [SOURCES['CN_GS']], 'HISTORICAL',
                nose='blunt', nose_len_ratio=1.5, wing_type='fixed', wing_pairs=1,
                wing_span_ratio=2.6, wing_chord_ratio=1.0, wing_position=0.4,
                wing_sweep_deg=28.0, tail_type='cruciform', tail_span_ratio=1.8,
                booster=1, booster_len_ratio=0.22, booster_fins=4, bands=2, canister=1,
            ),
        ],
    ),
    family(
        'CN_ASM_YJ18', 'China', 'YJ-18 family', 'ASM', ['ASM', 'LAM'], 'cn_asm_yj18',
        [
            _entry(
                'CN_ASM_YJ18', 'YJ-18', 'YJ-18', 'ASM',
                '现代远程反舰巡航导弹', 'Modern_Cruise', 'Modern', '2010s-present',
                8,
                '游戏 T8 中国现代反舰主力：发射管布放、弹翼折叠，末段为独立超音速级。',
                '惯性 + 主动雷达', '涡喷 + 固体助推',
                ['TORPEDO_TUBE', 'VLS'], ['anti_ship', 'modern', 'long_range'],
                dim(8.2, 0.533, 2300, 'ESTIMATED', '公开资料存在多个版本，取与发射管匹配的级别近似。'),
                'HIGH', 'cruise_missile', ['underwater_launch', 'folding_wing', 'terminal_stage'],
                [SOURCES['CN_GS']], 'ACTIVE',
                nose='ogive', nose_len_ratio=2.4, wing_type='folding', wing_pairs=1,
                wing_span_ratio=3.2, wing_chord_ratio=1.0, wing_position=0.44,
                wing_sweep_deg=40.0, tail_type='cruciform', tail_span_ratio=2.4,
                booster=1, booster_len_ratio=0.34, booster_fins=4, bands=2, windows=0, canister=1,
            ),
            _entry(
                'CN_LAM_YJ18_LandAttack', 'YJ-18 对陆攻击型', 'YJ-18 LAM', 'LAM',
                '对陆攻击巡航导弹型号', 'Modern_Cruise', 'Modern', '2010s-present',
                8,
                '游戏 T8 对陆攻击分支：与反舰型共享发射系统，任务模块不同；公开资料有限，作为数据库条目与游戏占位。',
                '惯性 + 卫星定位 + 地形匹配', '涡喷 + 固体助推',
                ['TORPEDO_TUBE', 'VLS'], ['land_attack', 'modern', 'long_range'],
                dim(7.0, 0.533, 2000, 'GAMEPLAY_SCALE', '公开资料不足，按同族发射管级别估计。'),
                'DATABASE_ONLY', 'cruise_missile', ['underwater_launch', 'folding_wing', 'land_attack_kit'],
                [SOURCES['CN_GS']], 'UNKNOWN',
                nose='ogive', nose_len_ratio=2.8, wing_type='folding', wing_pairs=1,
                wing_span_ratio=3.8, wing_chord_ratio=1.1, wing_position=0.42,
                wing_sweep_deg=28.0, tail_type='cruciform', tail_span_ratio=2.0,
                booster=1, booster_len_ratio=0.3, booster_fins=4, bands=2, canister=1,
                notes='公开资料有限，confidence=GAMEPLAY、asset_priority=DATABASE_ONLY，不进入 3D 生产队列。',
            ),
        ],
    ),
    family(
        'RU_LAM_Granat', 'Russia', 'RK-55 Granat', 'LAM', ['LAM'], 'ru_lam_granat',
        [
            _entry(
                'RU_LAM_Granat', 'RK-55 Granat', 'Granat', 'LAM',
                '早期对陆攻击巡航导弹', 'Cold_War_Cruise', 'Cold War Late', '1980s-1990s',
                6,
                '游戏 T6 苏联对陆攻击节点：经发射管布放、弹翼弹出，与反舰导弹外形不同。',
                '惯性 + 地形匹配', '涡喷 + 固体助推',
                ['TORPEDO_TUBE'], ['land_attack', 'long_range'],
                dim(8.1, 0.53, 1700, 'ESTIMATED', '公开资料为级别近似。'),
                'MEDIUM', 'cruise_missile', ['underwater_launch', 'popout_wing'],
                [SOURCES['RU_FAS']], 'RETIRED',
                nose='ogive', nose_len_ratio=2.6, wing_type='popout', wing_pairs=1,
                wing_span_ratio=3.8, wing_chord_ratio=1.1, wing_position=0.44,
                wing_sweep_deg=28.0, tail_type='cruciform', tail_span_ratio=2.0,
                booster=1, booster_len_ratio=0.3, booster_fins=4, bands=2, canister=1,
            ),
        ],
    ),

    # ===================================================================
    # 反潜导弹 ASW
    # ===================================================================
    family(
        'US_ASW_SUBROC', 'USA', 'UUM-44 SUBROC', 'ASW', ['ASW'], 'us_asw_subroc',
        [
            _entry(
                'US_ASW_SUBROC', 'UUM-44 SUBROC', 'SUBROC', 'ASW',
                '潜射反潜火箭', 'Rocket_Delivered', 'Cold War', '1965-1989',
                5,
                '游戏 T5 远程反潜节点：发射管出水后飞行，细长弹体 + 固体助推段，与鱼雷外形明显不同。',
                '惯性飞行', '固体火箭',
                ['TORPEDO_TUBE'], ['anti_submarine', 'standoff'],
                dim(6.7, 0.533, 1800, 'PUBLIC_REFERENCE', '公开资料长度约 6.7 米。'),
                'MEDIUM', 'rocket_payload', ['tube_launched', 'solid_booster', 'aft_payload'],
                [SOURCES['US_FAS']], 'RETIRED',
                nose='blunt', nose_len_ratio=1.6, booster_len_ratio=0.35,
                booster_fins=4, booster_fin_span_ratio=1.4, payload_shape='torpedo',
                payload_separation_ring=1, fins=4, fin_span_ratio=1.3,
                fin_chord_ratio=0.9, bands=2,
            ),
        ],
    ),
    family(
        'US_ASW_SeaLance', 'USA', 'UUM-125 Sea Lance', 'ASW', ['ASW'], 'us_asw_sealance',
        [
            _entry(
                'US_ASW_SeaLance', 'UUM-125 Sea Lance', 'SeaLance', 'ASW',
                '潜射反潜导弹（取消）', 'Rocket_Delivered', 'Cold War Late', '1980s (cancelled)',
                6,
                '游戏 T6 未服役节点：仅入数据库，用于说明反潜导弹的换代尝试，不产出 3D 资产。',
                '惯性 + 声学载荷', '固体火箭',
                ['TORPEDO_TUBE', 'VLS'], ['anti_submarine', 'standoff'],
                dim(6.2, 0.533, 1400, 'ESTIMATED', '公开资料不足，按同代级别估计。'),
                'DATABASE_ONLY', 'rocket_payload', ['cancelled_project', 'solid_booster'],
                [SOURCES['US_FAS']], 'PLANNED',
                nose='blunt', nose_len_ratio=1.6, booster_len_ratio=0.35,
                booster_fins=4, booster_fin_span_ratio=1.4, payload_shape='torpedo',
                payload_separation_ring=1, fins=4, fin_span_ratio=1.3,
                fin_chord_ratio=0.9, bands=2,
            ),
        ],
    ),
    family(
        'RU_ASW_Vyuga', 'Russia', 'RPK-2 Vyuga', 'ASW', ['ASW'], 'ru_asw_vyuga',
        [
            _entry(
                'RU_ASW_Vyuga', 'RPK-2 Vyuga', 'Vyuga', 'ASW',
                '早期潜射反潜导弹', 'Rocket_Delivered', 'Cold War', '1969-1990s',
                4,
                '游戏 T4 反潜导弹起点：发射管布放、出水后飞行，弹体较短。',
                '惯性 + 声学载荷', '固体火箭',
                ['TORPEDO_TUBE'], ['anti_submarine', 'standoff'],
                dim(6.0, 0.533, 1800, 'ESTIMATED', '公开资料为级别近似。'),
                'MEDIUM', 'rocket_payload', ['tube_launched', 'solid_booster'],
                [SOURCES['RU_SHIPS'], SOURCES['RU_FAS']], 'RETIRED',
                nose='blunt', nose_len_ratio=1.4, booster_len_ratio=0.32,
                booster_fins=4, booster_fin_span_ratio=1.3, payload_shape='torpedo',
                payload_separation_ring=1, fins=4, fin_span_ratio=1.3,
                fin_chord_ratio=0.9, bands=2,
            ),
        ],
    ),
    family(
        'RU_ASW_Vodopad', 'Russia', 'RPK-6 Vodopad', 'ASW', ['ASW'], 'ru_asw_vodopad',
        [
            _entry(
                'RU_ASW_Vodopad', 'RPK-6 Vodopad', 'Vodopad', 'ASW',
                '潜射反潜导弹', 'Rocket_Delivered', 'Cold War Late', '1981-present',
                6,
                '游戏 T6 苏联反潜导弹主力：8 米级弹体、助推段与载荷段分界清晰。',
                '惯性 + 声学载荷', '固体火箭',
                ['TORPEDO_TUBE'], ['anti_submarine', 'standoff'],
                dim(8.2, 0.533, 2400, 'PUBLIC_REFERENCE', '公开资料长度约 8 米级。'),
                'MEDIUM', 'rocket_payload', ['tube_launched', 'solid_booster', 'payload_torpedo'],
                [SOURCES['RU_SHIPS'], SOURCES['RU_FAS']], 'RETIRED',
                nose='ogive', nose_len_ratio=1.8, booster_len_ratio=0.36,
                booster_fins=4, booster_fin_span_ratio=1.4, payload_shape='torpedo',
                payload_separation_ring=1, fins=4, fin_span_ratio=1.4,
                fin_chord_ratio=0.9, bands=3,
            ),
        ],
    ),
    family(
        'RU_ASW_Veter', 'Russia', 'RPK-7 Veter', 'ASW', ['ASW'], 'ru_asw_veter',
        [
            _entry(
                'RU_ASW_Veter', 'RPK-7 Veter', 'Veter', 'ASW',
                '远程反潜导弹', 'Rocket_Delivered', 'Cold War Late', '1980s-present',
                7,
                '游戏 T7 远程反潜节点：与 Vodopad 同族但弹体更长，载荷段比例不同。',
                '惯性 + 声学载荷', '固体火箭',
                ['TORPEDO_TUBE', 'VLS'], ['anti_submarine', 'standoff', 'long_range'],
                dim(8.9, 0.533, 2600, 'ESTIMATED', '公开资料为级别近似。'),
                'MEDIUM', 'rocket_payload', ['tube_launched', 'solid_booster', 'long_range'],
                [SOURCES['RU_SHIPS']], 'RETIRED',
                nose='ogive', nose_len_ratio=1.9, booster_len_ratio=0.38,
                booster_fins=4, booster_fin_span_ratio=1.4, payload_shape='torpedo',
                payload_separation_ring=1, fins=4, fin_span_ratio=1.4,
                fin_chord_ratio=1.0, bands=3,
            ),
        ],
    ),
    family(
        'RU_ASW_Otvet', 'Russia', '91R Otvet', 'ASW', ['ASW'], 'ru_asw_otvet',
        [
            _entry(
                'RU_ASW_Otvet', '91R Otvet', 'Otvet', 'ASW',
                '现代反潜导弹', 'Rocket_Delivered', 'Modern', '2010s-present',
                8,
                '游戏 T8 现代反潜节点：与 Yasen 级配套，弹体短而粗，适合垂直发射。',
                '惯性 + 声学载荷', '固体火箭',
                ['VLS', 'TORPEDO_TUBE'], ['anti_submarine', 'standoff', 'modern'],
                dim(6.5, 0.533, 2000, 'ESTIMATED', '公开资料为级别近似。'),
                'MEDIUM', 'rocket_payload', ['vls_launched', 'solid_booster', 'modern'],
                [SOURCES['RU_FAS']], 'ACTIVE',
                nose='ogive', nose_len_ratio=1.7, booster_len_ratio=0.34,
                booster_fins=4, booster_fin_span_ratio=1.3, payload_shape='torpedo',
                payload_separation_ring=1, fins=4, fin_span_ratio=1.3,
                fin_chord_ratio=0.9, bands=3,
            ),
        ],
    ),
    family(
        'CN_ASW_CY1', 'China', 'CY-1', 'ASW', ['ASW'], 'cn_asw_cy1',
        [
            _entry(
                'CN_ASW_CY1', 'CY-1 anti-submarine missile', 'CY-1', 'ASW',
                '潜射反潜导弹', 'Rocket_Delivered', 'Modern', '1990s-present',
                6,
                '游戏 T6 中国反潜导弹节点：公开资料有限，按可见外形（弹体 + 助推段）建模。',
                '惯性 + 声学载荷', '固体火箭',
                ['TORPEDO_TUBE'], ['anti_submarine', 'standoff'],
                dim(6.0, 0.533, 1800, 'ESTIMATED', '公开资料为级别近似。'),
                'LOW', 'rocket_payload', ['tube_launched', 'solid_booster'],
                [SOURCES['CN_GS']], 'UNKNOWN',
                nose='ogive', nose_len_ratio=1.7, booster_len_ratio=0.32,
                booster_fins=4, booster_fin_span_ratio=1.3, payload_shape='torpedo',
                payload_separation_ring=1, fins=4, fin_span_ratio=1.3,
                fin_chord_ratio=0.9, bands=2,
            ),
        ],
    ),
]
